use_frameworks!

platform :ios, '8.0'

target 'HttpClient_Example' do
  pod 'HttpClient', :path => '../HttpClient.podspec'

  target 'HttpClient_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
